---
- hosts: host1
  tasks: 
   - name: Record public IP of host1
     shell: wget -qO- http://ipecho.net/plain ; echo
     register: public_ip

- hosts: host2

  vars:
    host_ip: "{{ ansible_default_ipv4.address }}"
    first_ip: "{{ hostvars.host1.ansible_default_ipv4.address }}"
    first_public_ip: "{{ hostvars.host1.public_ip.stdout }}"

  tasks:
   - name: Install tools
     apt: name={{item}} state=latest
     sudo: yes
     with_items:
       - git
       - htop
       - vim

   - name: Checkout DevStack
     git: 
      repo: https://git.openstack.org/openstack-dev/devstack 
      dest: /home/ubuntu/devstack

   - name: Setup local.conf
     template: 
       src: local.conf.j2
       dest: /home/ubuntu/devstack/local.conf

   - name: Install DevStack compute node (async)
     shell: ./stack.sh chdir=/home/ubuntu/devstack
     async: 900
     poll: 5



